**Part** **1**

In [32]:
# 1st question
import numpy as np
arr= np.random.randint(0,1,(2,2))
print(arr)

[[0 0]
 [0 0]]


In [34]:
# 2nd question
import random
arr= np.random.randint(1,2,(4,2))
print(arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [35]:
# 3rd ,4th and 5th question
filled_array = np.full((3, 3),fill_value= 7)
print(filled_array)
ones_like = np.ones_like(filled_array)
print(ones_like)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
# 6th ques
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


**Part 2**

In [37]:
# Ques 1
import numpy as np
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [38]:
# Ques 2
import numpy as np
array_0_8= np.reshape((np.arange(0,9)),(3,3))
print(array_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
# Ques 3
import numpy as np
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
# Ques 4
import numpy as np
random_array = np.random.rand(30)
mean_arr = random_array.mean()
print(mean_arr)

0.4101329440308926


In [41]:
# Ques 5
import numpy as np
array = np.random.randint(1,100,size=(10,10))
min_val = array.min()
max_val = array.max()
print("The random elements array is: ",array)
print("The min value of the matrix is:",min_val)
print("The max value of the matrix is:",max_val)

The random elements array is:  [[87 53 11 22 38 17 52 86 94 45]
 [27 30 40 26 79 47 11 97 70 31]
 [27 92 17  9 13 14 21 90 79 42]
 [87 49 86 10 54 47  3 15 88 19]
 [52 17 55 12  9 40 49 78 46 40]
 [54 45 14 71 75 70 93 93 63 23]
 [75 25 37 11  4 92 77 23 76 15]
 [94 70 35 71 14 88 21 18  5 18]
 [45 90 20  2 63  5 92 35 16 73]
 [55 47  6 13 70  5 43 40 71 86]]
The min value of the matrix is: 2
The max value of the matrix is: 97


In [42]:
# Ques 6
import numpy as np
array = np.zeros((10,10))
print(array)
array[0][4]= 1
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
# Ques 7
import numpy as np
array = [1,2,0,0,4,0]
array.reverse()
# array.sort()
print(array)


[0, 4, 0, 0, 2, 1]


In [44]:
# Ques 8
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0,:]=1
array[-1,:] =1
array[:,0]=1
array[:,-1]=1
print(array)


[[1 1 1]
 [1 5 1]
 [1 1 1]]


In [45]:
# Ques 9
import numpy as np
check = np.random.randint(0,1,(8,8))
check[1::2, ::2] = 1
check[::2, 1::2] = 1
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Part 3**

In [46]:
# Ques 1
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = x+y
result2 = np.add(x,y)
print(result1)
print(result2)

v = np.array([9,10])
w = np.array([11,12])
result1 = np.add(v,w)
print(result1)

[[ 6  8]
 [10 13]]
[[ 6  8]
 [10 13]]
[20 22]


In [47]:
# Ques 2
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result = np.subtract(x,y)
print(result)

v = np.array([9,10])
w = np.array([11,12])
result = np.subtract(v,w)
print(result)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [48]:
# Ques 3
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

res1 = v*2
res2= w*3
res3 = x*4
res4=y*5

print(res1)
print(res2)
print(res3)
print(res4)

[18 20]
[33 36]
[[ 4  8]
 [12 20]]
[[25 30]
 [35 40]]


In [49]:
# Ques 4
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

square1 = np.square(v)
square2 = np.square(w)
square3 = np.square(x)
square4 = np.square(y)
print(square1,"\n", square2,"\n", square3,"\n", square4)

[ 81 100] 
 [121 144] 
 [[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]]


In [50]:
# Ques 5
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

result1 = np.dot(v,w)
result2 = np.dot(x,v)
result3 =np.dot(x,y)

print(result1)
print(result2)
print(result3)

219
[29 77]
[[19 22]
 [50 58]]


In [51]:
# Ques 6
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = np.concatenate((v,w))
result2 = np.concatenate((x,y),axis = 1)
print(result1)
print(result2)
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

[ 9 10 11 12]
[[1 2 5 6]
 [3 5 7 8]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
# Ques 7
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Part 4**

In [53]:
# Question 1
# Part 1
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv=np.linalg.inv(A)
result = np.dot(A_inv,A)
result = np.round(result, decimals=10)
I = np.eye(2,2)
# print(I)
if np.allclose(result,I) :
    print("Equal")
else:
    print("Not equal")

Equal


In [54]:
#part  2
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
res2 = np.matmul(B,A)
if np.allclose(res1,res2):
    print("Equal")
else:
    print("Not equal")

Not equal


In [55]:
#Part 3
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
transpAB = np.transpose(res1)
transpA = np.transpose(A)
transpB = np.transpose(B)
res2 = np.matmul(transpB,transpA)
if np.allclose(transpAB,res2):
        print("Equal")
else:
        print("Not equal")

Equal


In [57]:
# Ques 2 and 3
import numpy as np
A= ([[2,-3,1],
    [1,-1,2],
    [3,1,-1]])

B= ([-1],
    [-3],
    [9])

A_inv = np.linalg.inv(A)
res = np.dot(A_inv,B)
print(res)

[[ 2.]
 [ 1.]
 [-2.]]
